[build]
  command = "git submodule update --init --recursive && npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.5"
  HUGO_ENABLEGITINFO = "true"
  HUGO_TIMEOUT = 120


[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[context.production]
  command = "npm run build"

[context.production.environment]
  HUGO_BASEURL = "https://microcks.io/"
